{
  "swagger": "2.0",
  "info": {
    "title": "Smart Soft IT",
    "description": "Smart Soft IT",
    "termsOfService": "https://www.google.com/policies/terms/",
    "contact": {
      "email": "bdmotaleb33@gmail.com"
    },
    "license": {
      "name": "MIT License"
    },
    "version": "v1"
  },
  "host": "127.0.0.1:8000/api/v1",
  "schemes": [
      "http"
  ],
  "basePath": "/",
  "consumes": [
      "application/json"
  ],
  "produces": [
      "application/json"
  ],
  "securityDefinitions": {
    "Basic": {
      "type": "basic"
    },
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "Basic": [ ]
    },
    {
      "Bearer": [ ]
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "operationId": "login",
        "summary": "",
        "description": "Accepts/Returns nothing.",
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "required": true,
#            "schema": {
#              "$ref": "#/definitions/Login"
#            }
          }
        ],
        "responses": {
          "201": {
            "description": "",
#            "schema": {
#              "$ref": "#/definitions/Login"
#            }
          }
        },
        "tags": [
            "api"
        ]
      },
      "parameters": [ ]
    },
    "/logout": {
      "get": {
        "operationId": "logout",
        "summary": "",
        "description": "Accepts/Returns nothing.",
        "parameters": [ ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "tags": [
            "api"
        ]
      },
      "parameters": [ ]
    },
  }
}
